services:
  - type: web
    name: imall-api
    runtime: docker
    region: frankfurt
    dockerfilePath: ./Dockerfile.api
    autoDeploy: true
    disk:
      name: imall-api-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DOMAIN
        sync: false
      - key: NEXT_PUBLIC_DOMAIN
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_JWT_PUBLIC_KEY
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: SUPERADMIN_EMAIL
        sync: false
      - key: SUPERADMIN_PASSWORD
        sync: false
      - key: SEED_CATEGORIES
        sync: false
      - key: IMAGE_STORAGE_PROVIDER
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_BASE_FOLDER
        sync: false
      - key: CLOUDINARY_DELIVERY_TRANSFORMATION
        sync: false
      - key: KEEPZ_RSA_STATE_FILE
        sync: false
      - key: KEEPZ_DIRECT_SETTLEMENTS_BASE_URL
        sync: false
      - key: KEEPZ_DIRECT_SETTLEMENTS_CLIENT_ID
        sync: false
      - key: KEEPZ_DIRECT_SETTLEMENTS_CLIENT_SECRET
        sync: false
      - key: CREDO_ZERO_MERCHANT_ID
        sync: false

  - type: web
    name: imall
    runtime: docker
    region: frankfurt
    dockerfilePath: ./Dockerfile.web
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: imall-api
          property: hostport
      - key: NEXT_PUBLIC_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_JWT_PUBLIC_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DOMAIN
        sync: false
      - key: SUPERADMIN_EMAIL
        sync: false
      - key: SUPERADMIN_PASSWORD
        sync: false
