services:
  - type: web
    name: imall-api
    env: docker
    region: frankfurt
    dockerfilePath: ./Dockerfile.api
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DOMAIN
        sync: false
      - key: NEXT_PUBLIC_DOMAIN
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_JWT_PUBLIC_KEY
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: SUPERADMIN_EMAIL
        sync: false
      - key: SUPERADMIN_PASSWORD
        sync: false
      - key: SEED_CATEGORIES
        sync: false

  - type: web
    name: imall
    env: docker
    region: frankfurt
    dockerfilePath: ./Dockerfile.web
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: emakret-api
          property: hostport
      - key: NEXT_PUBLIC_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_JWT_PUBLIC_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DOMAIN
        sync: false
      - key: SUPERADMIN_EMAIL
        sync: false
      - key: SUPERADMIN_PASSWORD
        sync: false
